# Generated by Django 2.0.8 on 2018-09-11 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='standardpage',
            old_name='introduction',
            new_name='intro',
        ),
    ]
