# Generated by Django 2.0.8 on 2018-09-15 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20180914_0221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallerypage',
            old_name='introduction',
            new_name='intro',
        ),
    ]
