# Generated by Django 2.0.8 on 2018-11-13 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioindexpage',
            name='intro',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
