# Generated by Django 2.0.8 on 2018-11-18 19:05

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20181113_1932'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalSheetItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('item', models.CharField(max_length=250)),
            ],
            options={
                'abstract': False,
                'ordering': ['sort_order'],
            },
        ),
        migrations.AddField(
            model_name='portfoliopage',
            name='about',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='technicalsheetitem',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_sheet', to='portfolio.PortfolioPage'),
        ),
    ]
