# Generated by Django 2.0.8 on 2018-09-09 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='introduction',
            field=models.TextField(blank=True, help_text='Text to describe the page'),
        ),
    ]
