# Generated by Django 2.0.8 on 2018-11-01 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0021_image_file_hash'),
        ('home', '0006_auto_20180914_0221'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Landscape mode only; horizontal width between 1000px and 3000px.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='name',
            field=models.TextField(blank=True, help_text='Your Name'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='subtitle',
            field=models.TextField(default='Full Stack Developer', help_text='Ex: Full Stack Developer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='homepage',
            name='introduction',
            field=models.TextField(blank=True, help_text='A paragraph intro'),
        ),
    ]
