# Generated by Django 2.0.8 on 2018-11-15 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='demo_url',
            field=models.CharField(blank=True, help_text='Url for demo of project', max_length=250),
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='intro',
            field=models.CharField(blank=True, help_text='a couple sentance introduction', max_length=250),
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='project_url',
            field=models.CharField(blank=True, help_text='Ex: Github url', max_length=250),
        ),
    ]
