# Generated by Django 2.0.8 on 2018-11-19 18:42

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20181115_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectResources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=250)),
                ('url', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='projectpage',
            name='about',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='projectresources',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='projects.ProjectPage'),
        ),
    ]
