# Generated by Django 4.1.4 on 2022-12-23 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_blogpagetag_blogpage_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpage",
            name="tags",
        ),
    ]
